version: '3.2'

services:
  rabbitmq:
    image: rabbitmq:3.7.5-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: dingtoi
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    hostname: rabbitmq
