version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dingtoi
      POSTGRES_PASSWORD: Y-%"B}9 Z9:6r5o
      POSTGRES_DB: dingtoi
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
