version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dingtoi
      MONGO_INITDB_ROOT_USERNAME: dingtoi
      MONGO_INITDB_ROOT_PASSWORD: dingtoi
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
